No longer require `-D react_monomorphic`
With React 16 "ref" must be null, not undefined, or you get errors while rendering:

> Error: Expected ref to be a function or a string.

See https://github.com/facebook/react/issues/10649