Minor changes for React 16 (#80)
* No longer require `-D react_monomorphic`

With React 16 "ref" must be null, not undefined, or you get errors while rendering:

> Error: Expected ref to be a function or a string.

See https://github.com/facebook/react/issues/10649

* Add extern method for `React.hydrate()`

* Add `componentDidCatch()` lifecycle method.

Note: the documentation link points to the blog post, as this isn't included in the official React API docs yet (even though the React API docs seem to have been updated at the same time as the release?)

* Add ReactDOM.createPortal() to extern

* Change prop-types to be required from different NPM module

I thought about doing conditional compilation with a define to use the old import, but the new import should be compatible with old versions of React so I think I'll leave it.